# Generated by Django 4.0 on 2022-06-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', 'created_on', 'author', 'category', 'approved']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='approved',
        ),
    ]
